owner: Sampuke

repo: serveruptime

sites:
  - name: SouthLAnd Test Server
    check: "tcp-ping"
    url: 178.75.160.53
    port: 30120

status-website:
  baseUrl: /serveruptime
  logoUrl: https://github.com/Sampuke/serveruptime/blob/master/assets/logo96.png
  name: SouthLAnd
  introTitle: "**SouthLand** täältä näet serverin uptimen (eli onko servu toiminnassa)."
  introMessage: Tästä näkee onko servulla mahdollista pelata :)
  theme: dark
  themeUrl: https://github.com/Sampuke/serveruptime/blob/master/assets/my-custom-theme.css
  navbar:
    - title: Status
      href: https://sampuke.github.io/serveruptime
    - title: Pää Serveri
      href: https://sampuke.github.io/serveruptime/history/south-l-and-test-server
    - title: Liity
      href: fivem://connect/178.75.160.53:30120
    - title: Discord
      href: https://discord.gg/YXnAGJzwHZ

workflowSchedule:
  uptime: "3-58/5 * * * *"
