# Change these first
owner: Sampuke # Your GitHub organization or username, where this repository lives
repo: serveruptime # The name of this repository

sites:
  - name: SouthLAnd Test Server
    check: "tcp-ping"
    url: 178.75.160.53
    port: 30120

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /serveruptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/logo96.png
  name: SouthLAnd
  introTitle: "**SouthLand** täältä näet serverin uptimen (eli onko servu toiminnassa)."
  introMessage: Tästä näkee onko servulla mahdollista pelata :)
  navbar:
    - title: Status
      href: /
    - title: Join
      href: fivem://connect/178.75.160.53:30120
    - title: Discord
      href: https://discord.gg/YXnAGJzwHZ
workflowSchedule:
  uptime: "3-58/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
