# Change these first
owner: Sampuke # Your GitHub organization or username, where this repository lives
repo: serveruptime # The name of this repository

sites:
  - name: SouthLAnd Test Server
    check: "tcp-ping"
    url: 178.75.160.53
    port: 30120

status-website:
  baseUrl: /serveruptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/logo96.png
  name: SouthLAnd
  introTitle: "**SouthLand** täältä näet serverin uptimen (eli onko servu toiminnassa)."
  introMessage: Tästä näkee onko servulla mahdollista pelata :)
  theme: dark
  navbar:
    - title: Status
      href: https://sampuke.github.io/serveruptime
    - title: Join
      href: fivem://connect/178.75.160.53:30120
    - title: Discord
      href: https://discord.gg/YXnAGJzwHZ
workflowSchedule:
  uptime: "3-58/5 * * * *"
